- hosts: localhost
  vars:
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    - import_tasks: tasks/sshd.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/zsh.yml

