- name: Checkout dotfiles
  git:
    repo: 'https://github.com/czengler/dotfiles-linux'
    dest: ~/.config

- name: Symlink zsh config
  file:
    src: ~/.config/zsh/zshrc
    dest: ~/.zshrc
    state: link
