
- name: Install some little networking tools
  become: true
  apt:
    pkg:
    - tcpdump
    - nmap
    - curl
  tags: [ install, networking ]

- name: Stop and deactive systemd login daemon (sometimes slow as hell)
  become: true
  shell: systemctl mask systemd-logind
  tags: [ install, networking ]

- name: Set time to Europe/Berlin
  become: true
  shell: timedatectl set-timezone Europe/Berlin
  tags: [ install, networking, time ]
