- name: Install zsh
  become: true
  apt:
    name: zsh

- name: Get current user
  become: false
  shell: whoami
  register: username

- name: Get shell location
  shell: which zsh
  register: zsh_location

- name: change user shell to zsh
  become: true
  user:
    name: "{{ username.stdout }}"
    shell: "{{ zsh_location.stdout }}"

- name: Create plugin directory
  file:
    path: ~/.config/zsh/plugins
    state: directory
    mode: 0755

- name: Checkout fast syntax highlighting plugin
  git:
    repo: 'https://github.com/zdharma-continuum/fast-syntax-highlighting.git'
    dest: ~/.config/zsh/plugins

- name: Checkout autosuggestions plugin
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: ~/.config/zsh/plugins
